### ISSUE TITLE
Issue handling aperture macros (on by default in KiCAD 7 exports)

### ISSUE THREAD

**Issue by wormyrocks** [jaseg/gerbonara#1]
I get this error using `gerbolyze paste` to add an svg to gerbers exported from KiCad 7.0.2 with `kicad-cli`. Same problem persists using the plot dialog with default settings. Filing it under `gerbonara` as it seems like an issue with that package.
This is `gerbolyze/gerbonara` installed from pypi, but there's no difference in behavior from the 'build from source' instructions provided [here](https://github.com/jaseg/gerbolyze#id9).
I was able to fix it by using `--disable-aperture-macros` in the KiCad "Plot" dialog, which it says is "not recommended".
I'm assuming it isn't critical that this feature work perfectly but it should probably fail in a way that's transparent to the user.
Thanks for this project!
```
Traceback (most recent call last):
  File "/home/esk/.local/bin/gerbolyze", line 5, in <module>
Traceback (most recent call last):
  File "/home/esk/.local/bin/gerbolyze", line 5, in <module>
    gerbolyze.cli()
  File "/home/esk/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    gerbolyze.cli()
  File "/home/esk/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/esk/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    return self.main(*args, **kwargs)
  File "/home/esk/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/esk/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    rv = self.invoke(ctx)
  File "/home/esk/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/esk/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/esk/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/esk/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/esk/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/esk/.local/lib/python3.10/site-packages/gerbolyze/__init__.py", line 128, in paste
    return __callback(*args, **kwargs)
  File "/home/esk/.local/lib/python3.10/site-packages/gerbolyze/__init__.py", line 128, in paste
    stack.save_to_zipfile(output_gerbers)
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/layers.py", line 584, in save_to_zipfile
    stack.save_to_zipfile(output_gerbers)
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/layers.py", line 584, in save_to_zipfile
    out.write(layer.instance.write_to_bytes())
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/rs274x.py", line 324, in write_to_bytes
    out.write(layer.instance.write_to_bytes())
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/rs274x.py", line 324, in write_to_bytes
    return '\n'.join(self._generate_statements(settings, drop_comments=drop_comments)).encode('utf-8')
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/rs274x.py", line 270, in _generate_statements
    return '\n'.join(self._generate_statements(settings, drop_comments=drop_comments)).encode('utf-8')
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/rs274x.py", line 270, in _generate_statements
    macro_def = am_stmt(aperture.rotated().macro)
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/rs274x.py", line 259, in <lambda>
    macro_def = am_stmt(aperture.rotated().macro)
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/rs274x.py", line 259, in <lambda>
    am_stmt = lambda macro: f'%AM{macro.name}*\n{macro.to_gerber(unit=settings.unit)}*\n%'
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/aperture_macros/parse.py", line 123, in to_gerber
    am_stmt = lambda macro: f'%AM{macro.name}*\n{macro.to_gerber(unit=settings.unit)}*\n%'
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/aperture_macros/parse.py", line 123, in to_gerber
    comments = [ c.to_gerber() for c in self.comments ]
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/aperture_macros/parse.py", line 123, in <listcomp>
    comments = [ c.to_gerber() for c in self.comments ]
  File "/home/esk/.local/lib/python3.10/site-packages/gerbonara/aperture_macros/parse.py", line 123, in <listcomp>
    comments = [ c.to_gerber() for c in self.comments ]
    comments = [ c.to_gerber() for c in self.comments ]
AttributeError: 'str' object has no attribute 'to_gerber'
AttributeError: 'str' object has no attribute 'to_gerber'
```

**Comment by jaseg** [comment]
This is fixed in v1.2.0
